// Configuration-driven layer registry. Every layer declares its source,
// license, attribution and cache policy so nothing is hard-coded in app logic.
// Cache policies are enforced by the service worker (see vite.config.ts):
//   precache   – bundled with the app at build time
//   cache-first – fetched on demand, then served from Cache Storage
//   forecast    – like cache-first but expires within a day (model output changes hourly)

import type { TileFilter } from './tileFilters'
import type { InfoSpec } from './featureInfo'

export type LayerKind = 'xyz' | 'wms' | 'geojson' | 'computed'
export type Category = 'aquaculture' | 'seabed' | 'ocean' | 'environment' | 'fisheries' | 'shipping'

/** Overlay tabs in display order, with the importance rank of layers inside each. */
export const CATEGORIES: { id: Category; title: string; order: string[] }[] = [
  { id: 'aquaculture', title: 'Aquaculture', order: ['localities', 'lice-week', 'lice-heat', 'site-polygons', 'treatment-heat', 'prod-areas', 'nytek', 'disease-zones', 'escapes', 'current-points', 'deleted-sites'] },
  { id: 'seabed', title: 'Seabed', order: ['dybdedata', 'ngu-anchoring', 'ngu-sediment', 'ngu-deposition', 'ngu-slope'] },
  { id: 'ocean', title: 'Ocean', order: ['norkyst-current', 'norkyst-arrows', 'norkyst-temp', 'norkyst-salinity'] },
  { id: 'environment', title: 'Environment', order: ['naturvern', 'bunnhabitat', 'gyteomraader', 'salmon-fjords', 'coral-bans', 'shellfish'] },
  { id: 'fisheries', title: 'Fisheries', order: ['fishing-passive', 'fishing-active', 'fishing-activity', 'cod-spawning', 'lock-sites'] },
  { id: 'shipping', title: 'Shipping', order: ['fairways', 'ais-density-2024', 'ais-density-month', 'ais-density', 'fairway-area', 'ship-anchorages'] },
]
export type CachePolicy = 'precache' | 'cache-first' | 'forecast'

export interface LayerDef {
  id: string
  title: string
  group: 'base' | 'overlay'
  /** Overlay tab; required for overlays. */
  category?: Category
  kind: LayerKind
  /** XYZ tile template, WMS endpoint, or bundled data path (relative to BASE_URL). */
  url: string
  wmsLayers?: string
  /** Extra WMS query parameters (styles, colour scales, ...). */
  params?: Record<string, string>
  /** Legend image URL shown in the layer panel when enabled. */
  legend?: string
  /** How a GeoJSON layer is drawn (default circle). */
  render?: 'circle' | 'fill' | 'dots'
  /** Client-side per-pixel alpha for density images (see lib/tileFilters.ts). */
  tileFilter?: TileFilter
  /** Hover lookup (GetFeatureInfo) configuration; density layers are sampled from decoded tiles instead. */
  info?: InfoSpec
  organisation: string
  license: string
  attribution: string
  cache: CachePolicy
  opacity?: number
  maxzoom?: number
  description?: string
}

const KV = 'https://cache.kartverket.no/v1/wmts/1.0.0'
const NGU = 'https://geo.ngu.no/mapserver/MarineGrunnkartWMS'
const NORKYST = 'https://thredds.met.no/thredds/wms/fou-hi/norkystv3_800m_m00_be'
const KYSTVERKET = 'https://services.kystverket.no/wms.ashx'
const AIS = 'https://wms-geo.kystverket.no/density'
const MARTRAF = 'https://kystdatahuset.no/ws/api/raster-frequency/mapserver?map=/etc/mapserver/barentswatch.map'
const KV_ATTR = '© Kartverket'
const CC4 = 'CC BY 4.0'
const NLOD = 'NLOD 2.0'

export const LAYERS: LayerDef[] = [
  {
    id: 'topo',
    title: 'Topographic (Kartverket)',
    group: 'base',
    kind: 'xyz',
    url: `${KV}/topo/default/webmercator/{z}/{y}/{x}.png`,
    organisation: 'Kartverket',
    license: CC4,
    attribution: KV_ATTR,
    cache: 'cache-first',
    maxzoom: 18,
  },
  {
    id: 'topograatone',
    title: 'Topographic greytone (Kartverket)',
    group: 'base',
    kind: 'xyz',
    url: `${KV}/topograatone/default/webmercator/{z}/{y}/{x}.png`,
    organisation: 'Kartverket',
    license: CC4,
    attribution: KV_ATTR,
    cache: 'cache-first',
    maxzoom: 18,
  },
  {
    id: 'sjokart',
    title: 'Nautical chart (Kartverket)',
    group: 'base',
    kind: 'xyz',
    url: `${KV}/sjokartraster/default/webmercator/{z}/{y}/{x}.png`,
    organisation: 'Kartverket',
    license: CC4,
    attribution: KV_ATTR,
    cache: 'cache-first',
    maxzoom: 18,
  },
  {
    id: 'dybdedata',
    info: { kind: 'mapserver', layers: 'Dybdelag,Dybdekontur,grunne', keys: ['dybde', 'minimumsdybde', 'maksimumsdybde', 'dybdeverdi'], unit: 'm', presence: 'charted depth area' },
    category: 'seabed',
    title: 'Bathymetry (Kartverket Dybdedata)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://wms.geonorge.no/skwms1/wms.dybdedata2',
    wmsLayers: 'Dybdedata2',
    organisation: 'Kartverket',
    license: CC4,
    attribution: KV_ATTR,
    cache: 'cache-first',
    opacity: 0.7,
    description: 'Depth contours and soundings.',
  },
  {
    id: 'naturvern',
    info: { kind: 'arcgis', keys: ['navn', 'verneform'] },
    category: 'environment',
    title: 'Protected areas (Miljødirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://kart.miljodirektoratet.no/arcgis/services/vern/mapserver/WMSServer',
    wmsLayers: 'naturvern_klasser_omrade',
    organisation: 'Miljødirektoratet',
    license: NLOD,
    attribution: '© Miljødirektoratet',
    cache: 'cache-first',
    opacity: 0.6,
    description: 'Nature reserves, national parks and other protected areas.',
  },
  {
    id: 'bunnhabitat',
    info: { kind: 'arcgis', keys: ['navn', 'omradenavn'] },
    category: 'environment',
    title: 'Protected seabed habitats (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'verneomraader_bunnhabitat',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.6,
    description: 'Coral reefs and other protected bottom habitats.',
  },
  {
    id: 'prod-areas',
    info: { kind: 'arcgis', keys: ['Navn', 'status', 'Område'] },
    category: 'aquaculture',
    title: 'Production areas (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'produksjonsomraader',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.35,
    description: 'The 13 production areas of the traffic-light system with their current colour status.',
  },
  {
    id: 'deleted-sites',
    category: 'aquaculture',
    title: 'Deleted localities (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'geojson',
    render: 'circle',
    url: 'data/deleted_localities.geojson',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'precache',
    description: 'Former farm positions withdrawn from Akvakulturregisteret, with their register entry; click one for its details.',
  },
  {
    id: 'nytek',
    info: { kind: 'arcgis', keys: ['loknavn', 'loknr', 'innehaver', 'bottom_attachmenttype', 'bottom_depth', 'inspeksjonsorgan', 'sertif_til_dato'] },
    category: 'aquaculture',
    title: 'NYTEK moorings (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'nytek_areal,nytek_forankringsliner,nytek_forankring',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.8,
    description: 'Certified installation areas, mooring lines and anchor points with bottom depth, from NYTEK installation certificates.',
  },
  {
    id: 'current-points',
    info: { kind: 'arcgis', keys: ['navn', 'loknr', 'dato_sertifikat', 'organisasjon'], presence: 'current measurement point' },
    category: 'aquaculture',
    title: 'Current measurement points (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'nytek_strommaalingspunkt',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.9,
    description: 'Positions where farms measured currents for their NYTEK certification.',
  },
  {
    id: 'escapes',
    info: { kind: 'arcgis', keys: ['navn', 'art', 'antall_romt_estimert', 'rommingsdato', 'selskapsnavn'], presence: 'escape event' },
    category: 'aquaculture',
    title: 'Escapes (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'romming',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.9,
    description: 'Reported fish escape events.',
  },
  {
    id: 'disease-zones',
    info: { kind: 'arcgis', keys: ['sykdommer', 'status_sykdom', 'lokalitetsnummer', 'dato_paavist'], presence: 'PD/ILA zone' },
    category: 'aquaculture',
    title: 'PD and ILA zones (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'pd_pancreas_disease,ila_infeksios_lakseanemi',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.4,
    description: 'Control and surveillance zones for pancreas disease and infectious salmon anaemia.',
  },
  {
    id: 'salmon-fjords',
    info: { kind: 'arcgis', keys: ['fjord', 'region', 'kommune'], presence: 'national salmon fjord' },
    category: 'environment',
    title: 'National salmon fjords (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'nasjonale_laksefjorder',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.4,
    description: 'Fjords protected for wild salmon where new salmon farming is not permitted.',
  },
  {
    id: 'coral-bans',
    info: { kind: 'arcgis', keys: ['omraade', 'paragraf', 'info'], presence: 'coral reef protection' },
    category: 'environment',
    title: 'Coral reef bans (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'korallrev_forbudsomraade',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.6,
    description: 'Areas where fishing gear that can damage coral reefs is banned.',
  },
  {
    id: 'shellfish',
    info: { kind: 'arcgis', keys: ['art_norsk', 'stedsnavn', 'status'], presence: 'shellfish bed' },
    category: 'environment',
    title: 'Shellfish beds (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'skjellforekomst',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.6,
    description: 'Registered shellfish occurrences.',
  },
  {
    id: 'fishing-passive',
    info: { kind: 'arcgis', keys: ['stedsnavn', 'redskap', 'arter', 'brukere'] },
    category: 'fisheries',
    title: 'Fishing grounds, passive gear (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'fiskeplasser_passive_redskap',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.5,
    description: 'Fishing grounds for nets, lines and pots reported by local fishers, with species and gear.',
  },
  {
    id: 'fishing-active',
    info: { kind: 'arcgis', keys: ['stedsnavn', 'redskap', 'arter', 'brukere'] },
    category: 'fisheries',
    title: 'Fishing grounds, active gear (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'fiskeplasser_aktive_redskap',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.5,
    description: 'Fishing grounds for trawl, seine and Danish seine reported by fishers.',
  },
  {
    id: 'fishing-activity',
    info: { kind: 'arcgis', keys: ['UniqueValue.Pixel Value'], presence: 'fishing activity' },
    category: 'fisheries',
    title: 'Fishing activity since 2011 (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'fiskeriaktivitet_alle_redskap_fra_2011',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.6,
    description: 'Density of fishing activity from vessel tracking, all gear types, since 2011.',
  },
  {
    id: 'lock-sites',
    info: { kind: 'arcgis', keys: ['stedsnavn', 'alle_arter', 'beskriv_brukere'], presence: 'lock-up site' },
    category: 'fisheries',
    title: 'Seine lock-up sites (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'laassettingsplasser',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.8,
    description: 'Sites where purse-seine catches are held in nets before delivery.',
  },
  {
    id: 'cod-spawning',
    info: { kind: 'arcgis', keys: ['navn', 'gytefverdi', 'omradebesk'], presence: 'cod spawning field' },
    category: 'fisheries',
    title: 'Cod spawning fields (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'gytefelt_torsk_mb',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.5,
    description: 'Coastal cod spawning fields mapped by the Institute of Marine Research.',
  },
  {
    id: 'gyteomraader',
    info: { kind: 'arcgis', keys: ['art', 'navn'] },
    category: 'environment',
    title: 'Spawning areas (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'wms',
    url: 'https://gis.fiskeridir.no/server/services/fiskeridirWMS/MapServer/WMSServer',
    wmsLayers: 'gyteomraader',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'cache-first',
    opacity: 0.6,
    description: 'Fish spawning grounds reported by fishers.',
  },
  {
    id: 'ngu-sediment',
    info: { kind: 'mapserver', layers: 'Kornstorrelse_Det', keys: ['kornstorrelse', 'beskrivelse'] },
    category: 'seabed',
    title: 'Seabed sediment grain size (NGU)',
    group: 'overlay',
    kind: 'wms',
    url: NGU,
    wmsLayers: 'Sedimentkornstorrelse',
    legend: `${NGU}?service=WMS&request=GetLegendGraphic&version=1.3.0&layer=Sedimentkornstorrelse&format=image/png&sld_version=1.1.0`,
    organisation: 'NGU',
    license: NLOD,
    attribution: '© NGU',
    cache: 'cache-first',
    opacity: 0.7,
    description: 'Marine base maps; coverage limited to surveyed areas.',
  },
  {
    id: 'ngu-anchoring',
    info: { kind: 'mapserver', layers: 'Ankringsforhold', keys: ['ankringsforhold', 'beskrivelse'] },
    category: 'seabed',
    title: 'Anchoring conditions (NGU)',
    group: 'overlay',
    kind: 'wms',
    url: NGU,
    wmsLayers: 'Ankringsforhold',
    legend: `${NGU}?service=WMS&request=GetLegendGraphic&version=1.3.0&layer=Ankringsforhold&format=image/png&sld_version=1.1.0`,
    organisation: 'NGU',
    license: NLOD,
    attribution: '© NGU',
    cache: 'cache-first',
    opacity: 0.7,
    description: 'Seabed suitability for anchoring, from sediment and terrain.',
  },
  {
    id: 'ngu-deposition',
    info: { kind: 'mapserver', layers: 'Bunnfellingsomrader', keys: ['bunnfelling', 'beskrivelse'] },
    category: 'seabed',
    title: 'Deposition areas (NGU)',
    group: 'overlay',
    kind: 'wms',
    url: NGU,
    wmsLayers: 'Bunnfellingsomrader',
    legend: `${NGU}?service=WMS&request=GetLegendGraphic&version=1.3.0&layer=Bunnfellingsomrader&format=image/png&sld_version=1.1.0`,
    organisation: 'NGU',
    license: NLOD,
    attribution: '© NGU',
    cache: 'cache-first',
    opacity: 0.7,
    description: 'Areas where fine material settles; proxy for waste accumulation.',
  },
  {
    id: 'ngu-slope',
    info: { kind: 'mapserver', layers: 'Helning', keys: ['helning', 'beskrivelse'] },
    category: 'seabed',
    title: 'Seabed slope (NGU)',
    group: 'overlay',
    kind: 'wms',
    url: NGU,
    wmsLayers: 'Helning',
    legend: `${NGU}?service=WMS&request=GetLegendGraphic&version=1.3.0&layer=Helning&format=image/png&sld_version=1.1.0`,
    organisation: 'NGU',
    license: NLOD,
    attribution: '© NGU',
    cache: 'cache-first',
    opacity: 0.7,
  },
  {
    id: 'norkyst-temp',
    info: { kind: 'ncwms', unit: '°C' },
    category: 'ocean',
    title: 'Sea surface temperature (NorKyst v3)',
    group: 'overlay',
    kind: 'wms',
    url: NORKYST,
    wmsLayers: 'temperature',
    params: { styles: 'default-scalar/x-Rainbow', colorscalerange: '0,20' },
    legend: `${NORKYST}?REQUEST=GetLegendGraphic&LAYER=temperature&PALETTE=x-Rainbow&COLORSCALERANGE=0,20&WIDTH=60&HEIGHT=200&FORMAT=image/png`,
    organisation: 'MET Norway',
    license: CC4,
    attribution: '© MET Norway, NorKyst v3',
    cache: 'forecast',
    opacity: 0.65,
    description: 'Latest 800 m model hour, 0–20 °C.',
  },
  {
    id: 'norkyst-salinity',
    info: { kind: 'ncwms', unit: 'PSU' },
    category: 'ocean',
    title: 'Sea surface salinity (NorKyst v3)',
    group: 'overlay',
    kind: 'wms',
    url: NORKYST,
    wmsLayers: 'salinity',
    params: { styles: 'default-scalar/x-Rainbow', colorscalerange: '20,35' },
    legend: `${NORKYST}?REQUEST=GetLegendGraphic&LAYER=salinity&PALETTE=x-Rainbow&COLORSCALERANGE=20,35&WIDTH=60&HEIGHT=200&FORMAT=image/png`,
    organisation: 'MET Norway',
    license: CC4,
    attribution: '© MET Norway, NorKyst v3',
    cache: 'forecast',
    opacity: 0.65,
    description: 'Latest 800 m model hour, 20–35 PSU; low values show river plumes.',
  },
  {
    id: 'norkyst-current',
    info: { kind: 'ncwms', unit: 'm/s' },
    category: 'ocean',
    title: 'Surface current speed (NorKyst v3)',
    group: 'overlay',
    kind: 'wms',
    url: NORKYST,
    wmsLayers: 'u_eastward:v_northward-mag',
    params: { styles: 'default-scalar/x-Rainbow', colorscalerange: '0,1' },
    legend: `${NORKYST}?REQUEST=GetLegendGraphic&LAYER=u_eastward:v_northward-mag&PALETTE=x-Rainbow&COLORSCALERANGE=0,1&WIDTH=60&HEIGHT=200&FORMAT=image/png`,
    organisation: 'MET Norway',
    license: CC4,
    attribution: '© MET Norway, NorKyst v3',
    cache: 'forecast',
    opacity: 0.65,
    description: 'Latest 800 m model hour, 0–1 m/s.',
  },
  {
    id: 'norkyst-arrows',
    info: { kind: 'ncwms', direction: true },
    category: 'ocean',
    title: 'Surface current direction (NorKyst v3)',
    group: 'overlay',
    kind: 'wms',
    url: NORKYST,
    wmsLayers: 'u_eastward:v_northward-dir',
    params: { styles: 'arrows' },
    organisation: 'MET Norway',
    license: CC4,
    attribution: '© MET Norway, NorKyst v3',
    cache: 'forecast',
    opacity: 0.9,
    description: 'Arrows for the latest model hour.',
  },
  {
    id: 'fairways',
    info: { kind: 'mapserver', keys: ['navn', 'ledtype', 'farledsnavn'], presence: 'on a main/secondary fairway' },
    category: 'shipping',
    title: 'Main and secondary fairways (Kystverket)',
    group: 'overlay',
    kind: 'wms',
    url: KYSTVERKET,
    wmsLayers: 'layer_552',
    organisation: 'Kystverket',
    license: NLOD,
    attribution: '© Kystverket',
    cache: 'cache-first',
    opacity: 0.9,
    description: 'Hovedled og biled, current fairway regulation.',
  },
  {
    id: 'fairway-area',
    info: { kind: 'mapserver', keys: ['navn', 'ledtype'], presence: 'inside a fairway area' },
    category: 'shipping',
    title: 'Fairway areas (Kystverket)',
    group: 'overlay',
    kind: 'wms',
    url: KYSTVERKET,
    wmsLayers: 'layer_554',
    organisation: 'Kystverket',
    license: NLOD,
    attribution: '© Kystverket',
    cache: 'cache-first',
    opacity: 0.5,
    description: 'Farledsareal: the regulated navigation corridor around fairways.',
  },
  {
    id: 'ship-anchorages',
    info: { kind: 'mapserver', keys: ['navn', 'type'], presence: 'inside a shipping anchorage area' },
    category: 'shipping',
    title: 'Shipping anchorage areas (Kystverket)',
    group: 'overlay',
    kind: 'wms',
    url: KYSTVERKET,
    wmsLayers: 'layer_888',
    organisation: 'Kystverket',
    license: NLOD,
    attribution: '© Kystverket',
    cache: 'cache-first',
    opacity: 0.7,
  },
  {
    id: 'ais-density-2024',
    category: 'shipping',
    tileFilter: 'ais-hue',
    title: 'AIS traffic density 2024 (Kystverket MarTraf)',
    group: 'overlay',
    kind: 'wms',
    url: MARTRAF,
    wmsLayers: 'martraf_yearly_density_wms_t',
    params: { time: '2024-01-01' },
    organisation: 'Kystverket',
    license: NLOD,
    attribution: '© Kystverket / Kystdatahuset',
    cache: 'cache-first',
    opacity: 0.7,
    description: 'Vessel traffic density for the full year 2024, 0.01° grid; low-traffic cells are faded.',
  },
  {
    id: 'ais-density-month',
    category: 'shipping',
    tileFilter: 'ais-hue',
    title: 'AIS traffic density, April 2025 (Kystverket MarTraf)',
    group: 'overlay',
    kind: 'wms',
    url: MARTRAF,
    wmsLayers: 'martraf_monthly_density_wms_t',
    params: { time: '2025-04-01' },
    organisation: 'Kystverket',
    license: NLOD,
    attribution: '© Kystverket / Kystdatahuset',
    cache: 'cache-first',
    opacity: 0.7,
    description: 'Latest month published by the MarTraf service (monthly series 2020-01 to 2025-04).',
  },
  {
    id: 'ais-density',
    category: 'shipping',
    tileFilter: 'ais-white',
    title: 'AIS vessel track density 2022, 1 km (Kystverket)',
    group: 'overlay',
    kind: 'wms',
    url: AIS,
    wmsLayers: 'ais_trackdensity_norway_2022_1000mx1000m',
    organisation: 'Kystverket',
    license: NLOD,
    attribution: '© Kystverket',
    cache: 'cache-first',
    opacity: 0.7,
    description: 'Vessel track density from AIS, 1 km grid, full year 2022; low-traffic cells are faded.',
  },
  {
    id: 'lice-week',
    category: 'aquaculture',
    title: 'Lice per week',
    group: 'overlay',
    kind: 'computed',
    render: 'dots',
    url: '',
    organisation: 'BarentsWatch',
    license: NLOD,
    attribution: '© BarentsWatch',
    cache: 'precache',
    description: 'Colours every locality by its reported adult female lice in the week chosen on the slider.',
  },
  {
    id: 'lice-heat',
    category: 'aquaculture',
    title: 'Lice pressure per week',
    group: 'overlay',
    kind: 'computed',
    url: '',
    organisation: 'BarentsWatch',
    license: NLOD,
    attribution: '© BarentsWatch',
    cache: 'precache',
    description: 'Kernel-weighted mean of the reported lice within R km for the chosen week; computed on the device.',
  },
  {
    id: 'treatment-heat',
    category: 'aquaculture',
    title: 'Treatment intensity, last 4 years',
    group: 'overlay',
    kind: 'computed',
    url: '',
    organisation: 'BarentsWatch',
    license: NLOD,
    attribution: '© BarentsWatch',
    cache: 'precache',
    description: 'Share of production weeks with a lice treatment, smoothed over farms within R km; computed on the device.',
  },
  {
    id: 'site-polygons',
    category: 'aquaculture',
    title: 'Aquaculture site borders (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'geojson',
    render: 'fill',
    url: 'data/site_polygons.geojson',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'precache',
    description: 'Licensed site outlines from Akvakulturregisteret, snapshot bundled with the app.',
  },
  {
    id: 'localities',
    category: 'aquaculture',
    title: 'Aquaculture localities (Fiskeridirektoratet)',
    group: 'overlay',
    kind: 'geojson',
    url: 'data/localities.geojson',
    organisation: 'Fiskeridirektoratet',
    license: NLOD,
    attribution: '© Fiskeridirektoratet',
    cache: 'precache',
    description: 'Active localities from Akvakulturregisteret, snapshot bundled with the app.',
  },
]

export const LOCALITIES_LAYER = 'localities'
export const SALMON_COLOUR = '#f28c28'
export const OTHER_COLOUR = '#2a9d8f'
export const LEGEND = [
  { colour: SALMON_COLOUR, label: 'Salmon / trout locality' },
  { colour: OTHER_COLOUR, label: 'Other species' },
]

export const BASE_LAYERS = LAYERS.filter((l) => l.group === 'base')
export const OVERLAY_LAYERS = LAYERS.filter((l) => l.group === 'overlay')

/** Overlays of one tab, most important first (registry order for anything unranked). */
export function overlaysIn(category: Category): LayerDef[] {
  const order = CATEGORIES.find((c) => c.id === category)?.order ?? []
  const rank = (l: LayerDef) => (order.includes(l.id) ? order.indexOf(l.id) : order.length)
  return OVERLAY_LAYERS.filter((l) => l.category === category).sort((a, b) => rank(a) - rank(b))
}
export const layerById = (id: string) => LAYERS.find((l) => l.id === id)

export function wmsTileUrl(layer: LayerDef): string {
  const q = new URLSearchParams({
    service: 'WMS',
    request: 'GetMap',
    version: '1.3.0',
    layers: layer.wmsLayers ?? '',
    styles: '',
    crs: 'EPSG:3857',
    width: '256',
    height: '256',
    format: 'image/png',
    transparent: 'true',
    ...layer.params,
  })
  const sep = layer.url.includes('?') ? '&' : '?'
  return `${layer.url}${sep}${q.toString()}&bbox={bbox-epsg-3857}`
}

/** Legend images for a layer: an explicit `legend` when set, else one WMS GetLegendGraphic per sub-layer. */
export function legendUrls(l: LayerDef): string[] {
  if (l.legend) return [l.legend]
  if (l.kind !== 'wms' || !l.wmsLayers) return []
  const sep = l.url.includes('?') ? '&' : '?'
  return l.wmsLayers.split(',').map((name) => {
    const q = new URLSearchParams({ service: 'WMS', version: '1.3.0', request: 'GetLegendGraphic', format: 'image/png', layer: name.trim(), ...(l.params ?? {}) })
    return `${l.url}${sep}${q.toString()}`
  })
}
