// Fixed colour table for operators. Rules:
//  1. Every operator with 16 or more active sites has a fixed colour. Operators
//     are grouped by brand — the first word of the name (MOWI, SALMAR, LERØY …)
//     — so related companies share a hue: the brand's largest member gets the
//     base colour and the others lighter or darker variants of it.
//  2. The table is only ever appended (by scripts/gen-operator-colours.mjs after
//     a data refresh), so a company keeps its colour across releases. Brands are
//     ranked by total sites; the first eight brands use the colour-blind-checked
//     palette, later brands the extended sequence below.
//  3. Every other operator is grey on the map ("other operators").
//  4. An unlisted operator selected in the dropdown borrows, while selected, a
//     free variant of its brand's hue if the brand is in the table, otherwise
//     the first sequence colour not used by a selected table operator.
//  5. A site with several licence holders takes the colour of the first table
//     entry it matches, else of the first selected operator it matches, else grey.
//  6. This site's own line in charts is navy and the "all farms" comparison is
//     dark grey; neither is an operator colour.

/** Hue sequence: validated 8-hue palette first, then 32 extended hues. */
export const PALETTE = [
  '#2a78d6',
  '#eb6834',
  '#1baf7a',
  '#eda100',
  '#e87ba4',
  '#008300',
  '#4a3aa7',
  '#e34948',
  '#954e23',
  '#869523',
  '#319523',
  '#23956a',
  '#236a95',
  '#312395',
  '#862395',
  '#95234e',
  '#e2c05a',
  '#9ee25a',
  '#5ae27c',
  '#5ae2e2',
  '#5a7ce2',
  '#9e5ae2',
  '#e25ac0',
  '#e25a5a',
  '#a4b143',
  '#51b143',
  '#43b188',
  '#4388b1',
  '#5143b1',
  '#a443b1',
  '#b1436d',
  '#b16d43',
  '#4d8613',
  '#138630',
  '#138686',
  '#133086',
  '#4c1386',
  '#861369',
  '#861313',
  '#866913',
] as const

// BEGIN TABLE (generated by scripts/gen-operator-colours.mjs; rows are only ever appended)
export const OPERATOR_COLOURS: { brand: string; name: string; colour: string }[] = [
  { brand: 'MOWI', name: 'MOWI SEAWATER NORWAY AS', colour: '#2a78d6' },
  { brand: 'MOWI', name: 'MOWI ASA', colour: '#669ee2' },
  { brand: 'SALMAR', name: 'SALMAR OPPDRETT AS', colour: '#eb6834' },
  { brand: 'SALMAR', name: 'SALMAR FARMING AS', colour: '#f19875' },
  { brand: 'LERØY', name: 'LERØY MIDT SJØ AS', colour: '#1baf7a' },
  { brand: 'LERØY', name: 'LERØY VEST SJØ AS', colour: '#32dfa1' },
  { brand: 'LERØY', name: 'LERØY MIDT AS', colour: '#11714f' },
  { brand: 'LERØY', name: 'LERØY AURORA SJØ AS', colour: '#6cd8b2' },
  { brand: 'CERMAQ', name: 'CERMAQ NORWAY SALMON AS', colour: '#eda100' },
  { brand: 'NORGESKJELL', name: 'NORGESKJELL AS', colour: '#e87ba4' },
  { brand: 'NORDLAKS', name: 'NORDLAKS HAVBRUK AS', colour: '#008300' },
  { brand: 'NOVA', name: 'NOVA SEA HAVBRUK AS', colour: '#4a3aa7' },
  { brand: 'SINKABERG', name: 'SINKABERG HAVBRUK AS', colour: '#e34948' },
  { brand: 'ENGESUND', name: 'ENGESUND FISKEOPPDRETT AS', colour: '#954e23' },
  { brand: 'SEASHORE', name: 'SEASHORE SJØ AS', colour: '#869523' },
  { brand: 'MÅSØVAL', name: 'MÅSØVAL LISENS AS', colour: '#319523' },
  { brand: 'TROLAND', name: 'TROLAND LAKSEOPPDRETT AS', colour: '#23956a' },
  { brand: 'NORDSJØ', name: 'NORDSJØ FJORDBRUK AS', colour: '#236a95' },
  { brand: 'NORDLAND', name: 'NORDLAND FYLKESKOMMUNE', colour: '#312395' },
  { brand: 'BLOM', name: 'BLOM FISKEOPPDRETT AS', colour: '#862395' },
  { brand: 'FJELBERG', name: 'FJELBERG FJORDBRUK  AS', colour: '#95234e' },
  { brand: 'HOLMØY', name: 'HOLMØY HAVBRUK AS', colour: '#e2c05a' },
  { brand: 'ORGANIC', name: 'ORGANIC SEAFARM AS', colour: '#9ee25a' },
  { brand: 'SJØTROLL', name: 'SJØTROLL HAVBRUK SJØ AS', colour: '#5ae27c' },
  { brand: 'TOMBRE', name: 'TOMBRE FISKEANLEGG AS', colour: '#5ae2e2' },
  { brand: 'BOLAKS', name: 'BOLAKS SJØ AS', colour: '#5a7ce2' },
  { brand: 'EIDE', name: 'EIDE FJORDBRUK AS', colour: '#9e5ae2' },
  { brand: 'AUSTEVOLL', name: 'AUSTEVOLL MELAKS AS', colour: '#e25ac0' },
  { brand: 'ERKO', name: 'ERKO SEAFOOD AS', colour: '#e25a5a' },
  { brand: 'LINGALAKS', name: 'LINGALAKS AS', colour: '#a4b143' },
  { brand: 'NORDNORSK', name: 'NORDNORSK STAMFISK AS', colour: '#51b143' },
  { brand: 'VESTLAND', name: 'VESTLAND FYLKESKOMMUNE', colour: '#43b188' },
  { brand: 'AQUAGEN', name: 'AQUAGEN AS', colour: '#4388b1' },
  { brand: 'BENCHMARK', name: 'BENCHMARK GENETICS NORWAY AS', colour: '#5143b1' },
  { brand: 'FIRDA', name: 'FIRDA HAVBRUK AS', colour: '#a443b1' },
  { brand: 'KOBBEVIK', name: 'KOBBEVIK OG FURUHOLMEN OPPDRETT AS', colour: '#b1436d' },
  { brand: 'EMILSEN', name: 'EMILSEN HAVBRUK AS', colour: '#b16d43' },
  { brand: 'FYLKESNES', name: 'FYLKESNES FISK AS', colour: '#4d8613' },
  { brand: 'LANGØYLAKS', name: 'LANGØYLAKS AS', colour: '#138630' },
  { brand: 'TELAVÅG', name: 'TELAVÅG FISKEOPPDRETT AS', colour: '#138686' },
]
// END TABLE

export const OTHER_COLOUR = '#8d99a6'
export const SITE_COLOUR = '#0b3d5c'
export const ALL_FARMS_COLOUR = '#5d6b7a'

/** Brand = first word of the operator name. */
export const brandOf = (name: string) => name.trim().split(/\s+/)[0].toUpperCase()

// ---- colour helpers (mirrored in scripts/gen-operator-colours.mjs)
function hexToHsl(hex: string): [number, number, number] {
  const r = parseInt(hex.slice(1, 3), 16) / 255
  const g = parseInt(hex.slice(3, 5), 16) / 255
  const b = parseInt(hex.slice(5, 7), 16) / 255
  const max = Math.max(r, g, b)
  const min = Math.min(r, g, b)
  const l = (max + min) / 2
  if (max === min) return [0, 0, l]
  const d = max - min
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
  const h = max === r ? ((g - b) / d + (g < b ? 6 : 0)) / 6 : max === g ? ((b - r) / d + 2) / 6 : ((r - g) / d + 4) / 6
  return [h, s, l]
}
function hslToHex(h: number, s: number, l: number): string {
  const f = (n: number) => {
    const k = (n + h * 12) % 12
    const a = s * Math.min(l, 1 - l)
    return l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1))
  }
  return '#' + [f(0), f(8), f(4)].map((v) => Math.round(v * 255).toString(16).padStart(2, '0')).join('')
}
const VARIANTS: [number, number][] = [[0, 0], [0.14, 0], [-0.14, 0], [0.24, -0.15], [-0.22, 0.1], [0.08, -0.3]]
/** k-th lightness/saturation variant of a base colour (k = 0 is the base itself). */
export function variant(base: string, k: number): string {
  const [h, s, l] = hexToHsl(base)
  const [dl, ds] = VARIANTS[k % VARIANTS.length]
  return hslToHex(h, Math.max(0.15, Math.min(1, s + ds)), Math.max(0.25, Math.min(0.8, l + dl)))
}
/** Hue in degrees, for tests and grouping checks. */
export const hueOf = (hex: string) => Math.round(hexToHsl(hex)[0] * 360)

const TABLE = new Map(OPERATOR_COLOURS.map((o) => [o.name, o.colour]))
const BRAND_BASE = new Map<string, string>()
for (const o of OPERATOR_COLOURS) if (!BRAND_BASE.has(o.brand)) BRAND_BASE.set(o.brand, o.colour)

/** Colour for every operator that matters right now: the table plus borrowed colours for selected unlisted operators. */
export function paletteFor(selected: string[]): Map<string, string> {
  const out = new Map(TABLE)
  const usedHues = new Set(selected.filter((s) => TABLE.has(s)).map((s) => TABLE.get(s)!))
  for (const op of selected) {
    if (out.has(op)) continue
    const base = BRAND_BASE.get(brandOf(op))
    let colour: string
    if (base) {
      const taken = new Set([...out.values()])
      let k = 0
      while (taken.has(variant(base, k)) && k < VARIANTS.length * 2) k++
      colour = variant(base, k)
    } else {
      colour = PALETTE.find((c) => !usedHues.has(c)) ?? OTHER_COLOUR
      usedHues.add(colour)
    }
    out.set(op, colour)
  }
  return out
}

/** Colour of a site given its comma-separated operator list (rule 5). */
export function siteColour(operators: string, selected: string[] = []): string {
  const pal = paletteFor(selected)
  const ops = operators.split(',').map((s) => s.trim())
  for (const o of OPERATOR_COLOURS) if (ops.includes(o.name)) return o.colour
  for (const s of selected) if (ops.includes(s)) return pal.get(s)!
  return OTHER_COLOUR
}
