// Fixed colour table for operators. Rules:
//  1. Every operator with 16 or more active sites has a fixed colour. The table
//     is only ever appended (by scripts/gen-operator-colours.mjs after a data
//     refresh), so a company keeps its colour across releases; the first eight
//     rows are the largest operators on the colour-blind-checked palette, later
//     rows use the extended sequence below, which is distinct but not
//     guaranteed colour-blind safe.
//  2. Every other operator is grey on the map ("other operators").
//  3. When an unlisted operator is selected in the dropdown it borrows, for as
//     long as it is selected, the first sequence colour not used by any selected
//     table operator, in selection order.
//  4. A site with several licence holders takes the colour of the first table
//     entry it matches, else of the first selected operator it matches, else grey.
//  5. This site's own line in charts is navy and the "all farms" comparison is
//     dark grey; neither is an operator colour.

/** Colour sequence: validated 8-hue palette first, then 32 extended hues. */
export const PALETTE = [
  '#2a78d6',
  '#eb6834',
  '#1baf7a',
  '#eda100',
  '#e87ba4',
  '#008300',
  '#4a3aa7',
  '#e34948',
  '#954e23',
  '#869523',
  '#319523',
  '#23956a',
  '#236a95',
  '#312395',
  '#862395',
  '#95234e',
  '#e2c05a',
  '#9ee25a',
  '#5ae27c',
  '#5ae2e2',
  '#5a7ce2',
  '#9e5ae2',
  '#e25ac0',
  '#e25a5a',
  '#a4b143',
  '#51b143',
  '#43b188',
  '#4388b1',
  '#5143b1',
  '#a443b1',
  '#b1436d',
  '#b16d43',
  '#4d8613',
  '#138630',
  '#138686',
  '#133086',
  '#4c1386',
  '#861369',
  '#861313',
  '#866913',
] as const

// BEGIN TABLE (generated by scripts/gen-operator-colours.mjs; entries are only ever appended)
export const OPERATOR_COLOURS: { name: string; colour: string }[] = [
  { name: 'MOWI SEAWATER NORWAY AS', colour: '#2a78d6' },
  { name: 'SALMAR OPPDRETT AS', colour: '#eb6834' },
  { name: 'CERMAQ NORWAY SALMON AS', colour: '#1baf7a' },
  { name: 'NORGESKJELL AS', colour: '#eda100' },
  { name: 'MOWI ASA', colour: '#e87ba4' },
  { name: 'NORDLAKS HAVBRUK AS', colour: '#008300' },
  { name: 'LERØY MIDT SJØ AS', colour: '#4a3aa7' },
  { name: 'NOVA SEA HAVBRUK AS', colour: '#e34948' },
  { name: 'SALMAR FARMING AS', colour: '#954e23' },
  { name: 'LERØY VEST SJØ AS', colour: '#869523' },
  { name: 'LERØY MIDT AS', colour: '#319523' },
  { name: 'SINKABERG HAVBRUK AS', colour: '#23956a' },
  { name: 'ENGESUND FISKEOPPDRETT AS', colour: '#236a95' },
  { name: 'LERØY AURORA SJØ AS', colour: '#312395' },
  { name: 'SEASHORE SJØ AS', colour: '#862395' },
  { name: 'MÅSØVAL LISENS AS', colour: '#95234e' },
  { name: 'TROLAND LAKSEOPPDRETT AS', colour: '#e2c05a' },
  { name: 'NORDSJØ FJORDBRUK AS', colour: '#9ee25a' },
  { name: 'NORDLAND FYLKESKOMMUNE', colour: '#5ae27c' },
  { name: 'BLOM FISKEOPPDRETT AS', colour: '#5ae2e2' },
  { name: 'FJELBERG FJORDBRUK  AS', colour: '#5a7ce2' },
  { name: 'HOLMØY HAVBRUK AS', colour: '#9e5ae2' },
  { name: 'ORGANIC SEAFARM AS', colour: '#e25ac0' },
  { name: 'SJØTROLL HAVBRUK SJØ AS', colour: '#e25a5a' },
  { name: 'TOMBRE FISKEANLEGG AS', colour: '#a4b143' },
  { name: 'BOLAKS SJØ AS', colour: '#51b143' },
  { name: 'EIDE FJORDBRUK AS', colour: '#43b188' },
  { name: 'AUSTEVOLL MELAKS AS', colour: '#4388b1' },
  { name: 'ERKO SEAFOOD AS', colour: '#5143b1' },
  { name: 'LINGALAKS AS', colour: '#a443b1' },
  { name: 'NORDNORSK STAMFISK AS', colour: '#b1436d' },
  { name: 'VESTLAND FYLKESKOMMUNE', colour: '#b16d43' },
  { name: 'AQUAGEN AS', colour: '#4d8613' },
  { name: 'BENCHMARK GENETICS NORWAY AS', colour: '#138630' },
  { name: 'FIRDA HAVBRUK AS', colour: '#138686' },
  { name: 'KOBBEVIK OG FURUHOLMEN OPPDRETT AS', colour: '#133086' },
  { name: 'EMILSEN HAVBRUK AS', colour: '#4c1386' },
  { name: 'FYLKESNES FISK AS', colour: '#861369' },
  { name: 'LANGØYLAKS AS', colour: '#861313' },
  { name: 'TELAVÅG FISKEOPPDRETT AS', colour: '#866913' },
]
// END TABLE

export const OTHER_COLOUR = '#8d99a6'
export const SITE_COLOUR = '#0b3d5c'
export const ALL_FARMS_COLOUR = '#5d6b7a'

const TABLE = new Map(OPERATOR_COLOURS.map((o) => [o.name, o.colour]))

/** Colour for every operator that matters right now: the table plus borrowed colours for selected unlisted operators. */
export function paletteFor(selected: string[]): Map<string, string> {
  const out = new Map(TABLE)
  const used = new Set(selected.filter((s) => TABLE.has(s)).map((s) => TABLE.get(s)!))
  for (const op of selected) {
    if (out.has(op)) continue
    const free = PALETTE.find((c) => !used.has(c)) ?? OTHER_COLOUR
    used.add(free)
    out.set(op, free)
  }
  return out
}

/** Colour of a site given its comma-separated operator list (rule 4). */
export function siteColour(operators: string, selected: string[] = []): string {
  const pal = paletteFor(selected)
  const ops = operators.split(',').map((s) => s.trim())
  for (const o of OPERATOR_COLOURS) if (ops.includes(o.name)) return o.colour
  for (const s of selected) if (ops.includes(s)) return pal.get(s)!
  return OTHER_COLOUR
}
